export default [{value: "全部", label: "10"},
 {value: "CSS", label: "1",type:'1'},
{value: "HTML", label: "13"},
 {value: "JAVA", label: "14"},
 {value: "JavaScript", label: "15"},
{value: "嵌入式开发", label: "21"},
{value: "软件工程", label: "22"},
{value: "数据结构", label: "23"},
{value: "数据库", label: "31"},
 {value: "数字逻辑", label: "32"},
 {value: "计算机网络", label: "33"},
 {value: "计算机基础", label: "34"},
{value: "Vue", label: "35"}]
// export default [{value: "全部", type: "html"},
//  {value: "CSS", type: "2"},
// {value: "HTML", type: "13"},
//  {value: "JAVA", type: "14"},
//  {value: "JavaScript", type: "15"},
// {value: "嵌入式开发", type: "21"},
// {value: "软件工程", type: "22"},
// {value: "数据结构", type: "23"},
// {value: "数据库", type: "31"},
//  {value: "数字逻辑", type: "32"},
//  {value: "计算机网络", type: "33"},
//  {value: "计算机基础", type: "34"},
// {value: "Vue", type: "35"}]