export default [{value: "全部", label: "10"},
 {value: "CSS", label: "11"},
{value: "操作系统", label: "12"},
{value: "HTML", label: "13"},
 {value: "JAVA", label: "14"},
 {value: "JavaScript", label: "15"},
{value: "嵌入式开发", label: "21"},
{value: "软件工程", label: "22"},
{value: "数据结构", label: "23"},
{value: "数据库", label: "31"},
 {value: "数字逻辑", label: "32"},
 {value: "计算机网络", label: "33"},
 {value: "计算机基础", label: "34"},
{value: "Vue", label: "35"}]